"""Renderer for the Pixelify Sans bitmap-font modules.

Module format (one per size, generated by tools/rasterise_font.py):

    GLYPH_W, GLYPH_H, BPR, KERN : ints
    _FONT : dict[str, bytes]    # row-major MSB-first bitmap, BPR*GLYPH_H bytes

Usage:

    from lix import pixelfont
    font = pixelfont.load('pixelify_12')        # or 'pixelify_8', 'pixelify_24'
    font.text(d, "HELLO", x=10, y=20, color=api.WHITE)
    w = font.measure("HELLO")

Drawing cost is ~30 d.rect calls per glyph (only set bits emit a rect).
This is ~30× the cost of framebuf `d.text` — use for static menu titles,
not per-frame HUD readouts.
"""

from lix import api


_CACHE = {}      # module_name → PixelFont instance


def load(module_name):
    """Load + cache a font module from assets/fonts/optimized/<name>.py."""
    if module_name in _CACHE:
        return _CACHE[module_name]
    mod = __import__("assets.fonts.optimized." + module_name,
                     None, None, ["GLYPH_W", "GLYPH_H", "BPR", "KERN", "_FONT"])
    pf = PixelFont(mod)
    _CACHE[module_name] = pf
    return pf


class PixelFont:
    def __init__(self, mod):
        self.w     = mod.GLYPH_W
        self.h     = mod.GLYPH_H
        self.bpr   = mod.BPR
        self.kern  = mod.KERN
        self._font = mod._FONT
        # Proportional metrics: per-glyph (left_trim, advance). Scanned once
        # so text() can lay glyphs out edge-to-edge (with KERN) instead of
        # at fixed glyph-box width — fixes "P I X E L I F Y" looking spaced.
        self._metrics = self._compute_metrics()

    def _compute_metrics(self):
        bpr = self.bpr
        gw  = self.w
        gh  = self.h
        out = {}
        # Space — keep a sensible width since its bitmap is empty.
        space_w = max(3, gw // 3)
        for ch, bits in self._font.items():
            lo, hi = gw, -1
            for row in range(gh):
                row_off = row * bpr
                for col in range(gw):
                    if bits[row_off + (col >> 3)] & (0x80 >> (col & 7)):
                        if col < lo: lo = col
                        if col > hi: hi = col
            if hi < 0:
                out[ch] = (0, space_w)
            else:
                out[ch] = (lo, hi - lo + 1)
        return out

    # ── metrics ──────────────────────────────────────────────────────────
    def char_width(self, scale=1):
        return (self.w + self.kern) * scale

    def height(self, scale=1):
        return self.h * scale

    def measure(self, text, scale=1):
        if not text:
            return 0
        total = 0
        for ch in text:
            _, adv = self._metrics.get(ch, (0, self.w))
            total += adv + self.kern
        return (total - self.kern) * scale

    # ── render ───────────────────────────────────────────────────────────
    def char(self, d, ch, x, y, color, scale=1):
        """Draw a single glyph at (x, y) using its trimmed left edge."""
        bits = self._font.get(ch)
        if not bits:
            d.rect(x, y, self.w * scale, self.h * scale, color, fill=False)
            return
        lo, _adv = self._metrics.get(ch, (0, self.w))
        bpr = self.bpr
        gw  = self.w
        gh  = self.h
        for row in range(gh):
            row_off = row * bpr
            for col in range(lo, gw):
                if bits[row_off + (col >> 3)] & (0x80 >> (col & 7)):
                    d.rect(x + (col - lo) * scale, y + row * scale,
                           scale, scale, color, fill=True)

    def text(self, d, s, x, y, color=None, scale=1):
        """Draw a string at (x, y). Returns x after the last glyph."""
        if color is None:
            color = api.WHITE
        cx   = x
        kern = self.kern * scale
        for ch in s:
            _, adv = self._metrics.get(ch, (0, self.w))
            self.char(d, ch, cx, y, color, scale)
            cx += adv * scale + kern
        return cx

    def text_center(self, d, s, cx, y, color=None, scale=1):
        """Centre `s` horizontally around cx."""
        w = self.measure(s, scale)
        self.text(d, s, cx - w // 2, y, color, scale)
