"""Renderer for the Pixelify Sans bitmap-font modules.

Module format (one per size, generated by tools/rasterise_font.py):

    GLYPH_W, GLYPH_H, BPR, KERN : ints
    _FONT : dict[str, bytes]    # row-major MSB-first bitmap, BPR*GLYPH_H bytes

Usage:

    from lix import pixelfont
    font = pixelfont.load('pixelify_12')        # or 'pixelify_8', 'pixelify_24'
    font.text(d, "HELLO", x=10, y=20, color=api.WHITE)
    w = font.measure("HELLO")

Drawing cost is ~30 d.rect calls per glyph (only set bits emit a rect).
This is ~30× the cost of framebuf `d.text` — use for static menu titles,
not per-frame HUD readouts.
"""

from lix import api


_CACHE = {}      # module_name → PixelFont instance


def load(module_name):
    """Load + cache a font module from assets/fonts/optimized/<name>.py."""
    if module_name in _CACHE:
        return _CACHE[module_name]
    mod = __import__("assets.fonts.optimized." + module_name,
                     None, None, ["GLYPH_W", "GLYPH_H", "BPR", "KERN", "_FONT"])
    pf = PixelFont(mod)
    _CACHE[module_name] = pf
    return pf


class PixelFont:
    def __init__(self, mod):
        self.w     = mod.GLYPH_W
        self.h     = mod.GLYPH_H
        self.bpr   = mod.BPR
        self.kern  = mod.KERN
        self._font = mod._FONT

    # ── metrics ──────────────────────────────────────────────────────────
    def char_width(self, scale=1):
        return (self.w + self.kern) * scale

    def height(self, scale=1):
        return self.h * scale

    def measure(self, text, scale=1):
        if not text:
            return 0
        return (len(text) * (self.w + self.kern) - self.kern) * scale

    # ── render ───────────────────────────────────────────────────────────
    def char(self, d, ch, x, y, color, scale=1):
        """Draw a single glyph."""
        bits = self._font.get(ch)
        if not bits:
            # fallback: filled rectangle marker
            d.rect(x, y, self.w * scale, self.h * scale, color, fill=False)
            return
        bpr = self.bpr
        gw  = self.w
        gh  = self.h
        for row in range(gh):
            row_off = row * bpr
            for col in range(gw):
                byte = bits[row_off + (col >> 3)]
                if byte & (0x80 >> (col & 7)):
                    d.rect(x + col * scale, y + row * scale,
                           scale, scale, color, fill=True)

    def text(self, d, s, x, y, color=None, scale=1):
        """Draw a string at (x, y). Returns x after the last glyph."""
        if color is None:
            color = api.WHITE
        cx = x
        step = (self.w + self.kern) * scale
        for ch in s:
            self.char(d, ch, cx, y, color, scale)
            cx += step
        return cx

    def text_center(self, d, s, cx, y, color=None, scale=1):
        """Centre `s` horizontally around cx."""
        w = self.measure(s, scale)
        self.text(d, s, cx - w // 2, y, color, scale)
