"""Sprite-sheet helper for the Oreo Badge.

A SpriteSheet wraps a single big-endian RGB565 buffer that contains a grid of
equally-sized frames, and lets you extract individual frames or step through
an animation by frame index.

Usage (sheet generated by tools/optimize_assets.py — apps/<app>/assets/optimized/<name>.py):

    from oreoOS.sprite import SpriteSheet
    from apps.flappy.assets.optimized import mona_sheet as _data

    mona = SpriteSheet(_data, cols=7, rows=2)
    alive = mona.animation(row=0, frames=7)
    dead  = mona.animation(row=1, frames=5)

    # In your draw():
    sprite = alive.frame(idx)            # (data_bytes, w, h) tuple
    d.blit(*sprite, x, y)

`data` is a module with DATA / W / H attrs (the format `_write_py_module`
produces), so the sheet works identically on hardware and sim.
"""


class SpriteSheet:
    def __init__(self, data_mod, cols, rows):
        """
        data_mod : module exposing DATA (bytes), W, H of the whole sheet
        cols, rows : grid dimensions
        """
        self._buf  = data_mod.DATA if hasattr(data_mod, "DATA") else data_mod[0]
        self._sw   = data_mod.W    if hasattr(data_mod, "W")    else data_mod[1]
        self._sh   = data_mod.H    if hasattr(data_mod, "H")    else data_mod[2]
        self.cols  = cols
        self.rows  = rows
        self.fw    = self._sw // cols
        self.fh    = self._sh // rows
        self._cache = {}

    def sprite(self, col, row):
        """Return (frame_bytes, w, h) for the cell at (col, row)."""
        key = (col, row)
        c = self._cache.get(key)
        if c is not None:
            return c
        fw, fh = self.fw, self.fh
        sw     = self._sw
        # Extract `fh` rows of `fw` pixels each
        out = bytearray(fw * fh * 2)
        for fy in range(fh):
            src_y = row * fh + fy
            src_x = col * fw
            src_start = (src_y * sw + src_x) * 2
            out[fy * fw * 2: (fy + 1) * fw * 2] = self._buf[src_start: src_start + fw * 2]
        result = (bytes(out), fw, fh)
        self._cache[key] = result
        return result

    def animation(self, row=0, frames=None, start_col=0):
        """Build an Animation walking horizontally along `row`."""
        n = frames if frames is not None else (self.cols - start_col)
        return Animation(self, start_col, row, n)


class Animation:
    def __init__(self, sheet, start_col, row, count):
        self._sheet = sheet
        self._sc    = start_col
        self._row   = row
        self._count = count

    def count(self):
        return self._count

    def frame(self, idx):
        """Return the sprite tuple for the idx-th frame (clamped)."""
        i = int(idx)
        if i < 0:           i = 0
        elif i >= self._count: i = self._count - 1
        return self._sheet.sprite(self._sc + i, self._row)
