"""WiFi manager for the Oreo Badge.

Credentials come from a device-local `secrets.py` (generated by the deploy
script from your local .env file — never committed).

Usage:
    from oreoWare import wifi
    wifi.connect_from_config()
    wifi.is_connected()
"""

import network
import time

_wlan = None


def _get_wlan():
    global _wlan
    if _wlan is None:
        _wlan = network.WLAN(network.STA_IF)
    return _wlan


def _apply_power_cap(wlan):
    """Apply the secrets-baked TX-power dBm cap + power-save mode.

    Done as a best-effort: every `wlan.config(...)` call is wrapped in
    try/except so older / minimal MicroPython builds without one of these
    keys don't kill WiFi entirely.
    """
    try:
        from secrets import WIFI_TX_DBM
        try:
            wlan.config(txpower=int(WIFI_TX_DBM))
        except Exception:
            pass
    except Exception:
        pass
    try:
        from secrets import WIFI_POWERSAVE
        if WIFI_POWERSAVE:
            try:
                wlan.config(pm=wlan.PM_POWERSAVE)
            except Exception:
                pass
    except Exception:
        pass


def connect(ssid, password, timeout_ms=12000):
    wlan = _get_wlan()
    wlan.active(True)
    _apply_power_cap(wlan)
    if wlan.isconnected() and wlan.config("essid") == ssid:
        return True
    wlan.connect(ssid, password)
    start = time.ticks_ms()
    while not wlan.isconnected():
        if time.ticks_diff(time.ticks_ms(), start) > timeout_ms:
            return False
        time.sleep_ms(200)
    # Re-apply power-save AFTER association — some IDF versions reset PM
    # state on connect and need it set again to actually take effect.
    _apply_power_cap(wlan)
    return True


def connect_from_config():
    """Read secrets.py and connect if WIFI_SSID is set."""
    try:
        import secrets
        ssid = getattr(secrets, "WIFI_SSID", "")
        pw   = getattr(secrets, "WIFI_PASSWORD", "")
        if not ssid:
            return False
        return connect(ssid, pw)
    except Exception:
        return False


def disconnect():
    wlan = _get_wlan()
    wlan.disconnect()
    wlan.active(False)


def is_connected():
    try:
        return _get_wlan().isconnected()
    except Exception:
        return False


def ip():
    try:
        wlan = _get_wlan()
        if wlan.isconnected():
            return wlan.ifconfig()[0]
    except Exception:
        pass
    return None


def rssi():
    try:
        return _get_wlan().status("rssi")
    except Exception:
        return None
