"""WiFi manager for the Oreo Badge.

Saved networks live in `/wifi.json` on flash — a user-editable list
maintained by the WiFi settings app:

    [
      {"ssid": "Home",   "password": "...", "priority": 1, "metered": false},
      {"ssid": "Hotspot","password": "...", "priority": 5, "metered": true}
    ]

`connect_from_config()` walks the list in ascending-priority order
(lower number = tried first) and stops on the first SSID that
associates. `secrets.py` (generated by the deploy script) is only used
as a first-boot bootstrap: if `/wifi.json` doesn't exist yet AND
`secrets.WIFI_SSID` is set, we seed the json with that one network so
the badge associates immediately after the first flash.

Usage:
    from oreoWare import wifi
    wifi.connect_from_config()        # auto-pick best saved network
    wifi.is_connected()
    wifi.list_saved()                 # for the settings UI
    wifi.add_saved(ssid, pw, priority=10, metered=False)
    wifi.remove_saved(ssid)
    wifi.is_metered()                 # current link metered?
"""

import network
import time

try:
    import json as _json
except ImportError:
    _json = None

try:
    import os as _os
except ImportError:
    _os = None

_wlan = None

_SAVED_PATH       = "/wifi.json"
_PER_NET_TIMEOUT  = 8000     # ms — per-SSID cap so a wrong network is skipped fast


def _get_wlan():
    global _wlan
    if _wlan is None:
        _wlan = network.WLAN(network.STA_IF)
    return _wlan


def _apply_power_cap(wlan):
    """Apply the secrets-baked TX-power dBm cap + power-save mode.

    Done as a best-effort: every `wlan.config(...)` call is wrapped in
    try/except so older / minimal MicroPython builds without one of these
    keys don't kill WiFi entirely.
    """
    try:
        from secrets import WIFI_TX_DBM
        try:
            wlan.config(txpower=int(WIFI_TX_DBM))
        except Exception:
            pass
    except Exception:
        pass
    try:
        from secrets import WIFI_POWERSAVE
        if WIFI_POWERSAVE:
            try:
                wlan.config(pm=wlan.PM_POWERSAVE)
            except Exception:
                pass
    except Exception:
        pass


MDNS_HOSTNAME = "oreo"


def _apply_hostname(wlan):
    """Set the WiFi hostname so the ESP-IDF mDNS responder advertises
    `oreo.local` to the LAN. MicroPython builds vary in which kwarg key
    actually takes effect (`hostname` vs `dhcp_hostname`) so we try both.

    On most ESP32 IDF builds this is enough — IDF auto-spins up an mDNS
    responder for the configured hostname. Older builds that don't have
    the responder enabled will silently ignore this and `oreo.local`
    won't resolve; the badge will still be reachable by IP.
    """
    for key in ("hostname", "dhcp_hostname"):
        try:
            wlan.config(**{key: MDNS_HOSTNAME})
        except Exception:
            pass
    # Some forks expose a top-level mdns start. Best-effort.
    try:
        import network as _net
        if hasattr(_net, "hostname"):
            _net.hostname(MDNS_HOSTNAME)
    except Exception:
        pass


def connect(ssid, password, timeout_ms=12000):
    wlan = _get_wlan()
    wlan.active(True)
    # Hostname must be set BEFORE associate — the DHCP REQUEST carries
    # the hostname as Option 12 and the IDF mDNS service uses the same
    # name. Setting it after gets ignored by some routers.
    _apply_hostname(wlan)
    _apply_power_cap(wlan)
    if wlan.isconnected() and wlan.config("essid") == ssid:
        return True
    wlan.connect(ssid, password)
    start = time.ticks_ms()
    while not wlan.isconnected():
        if time.ticks_diff(time.ticks_ms(), start) > timeout_ms:
            return False
        time.sleep_ms(200)
    # Re-apply power-save + hostname AFTER association — some IDF
    # versions reset PM/hostname state on connect and need it set
    # again to actually take effect for the live link.
    _apply_power_cap(wlan)
    _apply_hostname(wlan)
    return True


def _exists(path):
    if _os is None:
        return False
    try:
        _os.stat(path)
        return True
    except OSError:
        return False


def _load_saved_raw():
    """Read `/wifi.json` as a Python list. Returns [] on missing/bad
    file — the caller is expected to bootstrap from secrets if so."""
    if _json is None or not _exists(_SAVED_PATH):
        return []
    try:
        with open(_SAVED_PATH) as f:
            data = _json.loads(f.read())
        if not isinstance(data, list):
            return []
        return data
    except Exception:
        return []


def _save_raw(networks):
    if _json is None:
        return False
    try:
        with open(_SAVED_PATH, "w") as f:
            f.write(_json.dumps(networks))
        return True
    except Exception:
        return False


def _bootstrap_from_secrets():
    """First-boot migration: if /wifi.json is missing AND secrets.py
    carries a single SSID, materialise it as a one-entry list. Idempotent
    — once /wifi.json exists this is a no-op."""
    if _exists(_SAVED_PATH):
        return _load_saved_raw()
    try:
        import secrets
        ssid = getattr(secrets, "WIFI_SSID", "")
        pw   = getattr(secrets, "WIFI_PASSWORD", "")
    except Exception:
        ssid, pw = "", ""
    if not ssid:
        return []
    seed = [{"ssid": ssid, "password": pw, "priority": 1, "metered": False}]
    _save_raw(seed)
    return seed


def list_saved():
    """Return the saved-networks list, sorted by ascending priority.
    Caller gets fresh dicts — mutating them doesn't affect on-disk state
    until save_saved() is called."""
    nets = _load_saved_raw() or _bootstrap_from_secrets()
    # Defensive copy + priority sort (None or missing → very high so
    # nameless entries sink to the bottom).
    def _key(n):
        try:
            return int(n.get("priority", 999))
        except Exception:
            return 999
    return sorted([dict(n) for n in nets if n.get("ssid")], key=_key)


def save_saved(networks):
    """Replace the entire saved list. Settings UI uses this after
    add / remove / reorder."""
    return _save_raw(list(networks))


def add_saved(ssid, password, priority=10, metered=False):
    """Add or update a single saved network. Matched by SSID; existing
    entries are overwritten so the user doesn't accumulate duplicates
    if they re-enter the same network."""
    nets = _load_saved_raw() or _bootstrap_from_secrets()
    out  = [n for n in nets if n.get("ssid") != ssid]
    out.append({
        "ssid":     ssid,
        "password": password or "",
        "priority": int(priority),
        "metered":  bool(metered),
    })
    return _save_raw(out)


def remove_saved(ssid):
    nets = _load_saved_raw()
    out  = [n for n in nets if n.get("ssid") != ssid]
    if len(out) == len(nets):
        return False
    return _save_raw(out)


def set_priority(ssid, priority):
    nets = _load_saved_raw()
    changed = False
    for n in nets:
        if n.get("ssid") == ssid:
            n["priority"] = int(priority)
            changed = True
            break
    if not changed:
        return False
    return _save_raw(nets)


def is_metered():
    """True iff the currently-associated SSID is flagged metered in
    /wifi.json. Used by OTA + Store to back off on tethered/hotspot
    connections so we don't burn the user's data plan."""
    cur = ssid()
    if not cur:
        return False
    for n in _load_saved_raw():
        if n.get("ssid") == cur:
            return bool(n.get("metered"))
    return False


def connect_from_config():
    """Try each saved network in priority order until one associates.

    Per-network timeout is short (_PER_NET_TIMEOUT) so a stale entry
    doesn't stall the boot. Returns True iff we associated to *any*
    saved SSID; False if the list is empty or every entry failed.
    """
    nets = list_saved()
    if not nets:
        return False
    for n in nets:
        ssid_ = n.get("ssid") or ""
        if not ssid_:
            continue
        pw = n.get("password") or ""
        try:
            ok = connect(ssid_, pw, timeout_ms=_PER_NET_TIMEOUT)
        except Exception:
            ok = False
        if ok:
            return True
    return False


def disconnect():
    wlan = _get_wlan()
    wlan.disconnect()
    wlan.active(False)


def is_connected():
    try:
        return _get_wlan().isconnected()
    except Exception:
        return False


def ip():
    try:
        wlan = _get_wlan()
        if wlan.isconnected():
            return wlan.ifconfig()[0]
    except Exception:
        pass
    return None


def rssi():
    try:
        return _get_wlan().status("rssi")
    except Exception:
        return None


def ssid():
    """Currently-associated SSID, or None if not connected."""
    try:
        wlan = _get_wlan()
        if wlan.isconnected():
            return wlan.config("essid")
    except Exception:
        pass
    return None


def ping(host="8.8.8.8", port=53, timeout_s=2):
    """TCP-connect "ping" to a known endpoint. MicroPython doesn't ship
    raw ICMP sockets on this port, so we time the TCP handshake to a
    cheap target (Google's DNS on port 53 by default).

    Returns (ok, rtt_ms). `ok=False, rtt_ms=None` on failure.
    """
    try:
        import socket as _s
    except ImportError:
        return (False, None)
    if not is_connected():
        return (False, None)
    try:
        addr = _s.getaddrinfo(host, port)[0][-1]
    except Exception:
        return (False, None)
    sock = _s.socket()
    try:
        sock.settimeout(timeout_s)
    except Exception:
        pass
    t0 = time.ticks_ms()
    try:
        sock.connect(addr)
        rtt = time.ticks_diff(time.ticks_ms(), t0)
        return (True, rtt)
    except Exception:
        return (False, None)
    finally:
        try:
            sock.close()
        except Exception:
            pass


def speed_test(bytes_=500_000, timeout_s=15):
    """Throughput probe: download `bytes_` from speed.cloudflare.com
    and report observed kbps. Cloudflare's __down endpoint serves an
    arbitrary number of bytes without auth and is geo-routed.

    Returns (ok, kbps, elapsed_ms). On failure, (False, 0, elapsed).
    Default size is 500 KB — enough to amortise SSL handshake on
    typical home WiFi, small enough to finish in seconds on EDGE/3G
    tethering.
    """
    try:
        import socket as _s
        import ssl    as _ssl
    except ImportError:
        return (False, 0, 0)
    if not is_connected():
        return (False, 0, 0)
    host = "speed.cloudflare.com"
    path = "/__down?bytes=%d" % int(bytes_)
    try:
        addr = _s.getaddrinfo(host, 443)[0][-1]
    except Exception:
        return (False, 0, 0)
    raw = None
    s   = None
    deadline = time.ticks_add(time.ticks_ms(), int(timeout_s * 1000))
    t0 = time.ticks_ms()
    received = 0
    body_started = False
    try:
        raw = _s.socket()
        try: raw.settimeout(timeout_s)
        except Exception: pass
        raw.connect(addr)
        s = _ssl.wrap_socket(raw, server_hostname=host)
        try: s.settimeout(timeout_s)
        except Exception: pass
        req = ("GET %s HTTP/1.1\r\nHost: %s\r\n"
               "User-Agent: OreoBadge-Speed\r\n"
               "Accept-Encoding: identity\r\n"
               "Connection: close\r\n\r\n") % (path, host)
        s.write(req.encode())
        head = b""
        # Read headers — we don't care about chunked decoding for the
        # bytes-counted speed metric; raw byte volume is what matters.
        while b"\r\n\r\n" not in head:
            if time.ticks_diff(deadline, time.ticks_ms()) <= 0:
                break
            try:
                chunk = s.read(2048)
            except Exception:
                break
            if not chunk:
                break
            head += chunk
            if len(head) > 16 * 1024:
                break
        # Count any payload bytes that arrived alongside the headers.
        sep = head.find(b"\r\n\r\n")
        if sep >= 0:
            body_started = True
            received     = len(head) - (sep + 4)
        # Drain the rest of the body counting bytes.
        while body_started:
            if time.ticks_diff(deadline, time.ticks_ms()) <= 0:
                break
            try:
                chunk = s.read(4096)
            except Exception:
                break
            if not chunk:
                break
            received += len(chunk)
            if received >= bytes_:
                break
    except Exception:
        pass
    finally:
        for h in (s, raw):
            try:
                if h is not None:
                    h.close()
            except Exception:
                pass
    elapsed = max(1, time.ticks_diff(time.ticks_ms(), t0))
    if received <= 0:
        return (False, 0, elapsed)
    kbps = int((received * 8) // elapsed)   # bytes*8 / ms = kbps
    return (True, kbps, elapsed)


def info():
    """One-shot snapshot for the WiFi detail screen.

    Returns a dict with `connected`, `ssid`, `ip`, `subnet`, `gateway`,
    `dns`, and `rssi`. Missing fields are None — the UI fills with '—'.
    """
    out = {"connected": False, "ssid": None,    "ip": None,
           "subnet":   None,  "gateway": None, "dns": None,
           "rssi":     None}
    try:
        wlan = _get_wlan()
        out["connected"] = bool(wlan.isconnected())
        if out["connected"]:
            cfg = wlan.ifconfig()    # (ip, subnet, gateway, dns)
            out["ip"]      = cfg[0]
            out["subnet"]  = cfg[1]
            out["gateway"] = cfg[2]
            out["dns"]     = cfg[3]
            try:
                out["ssid"] = wlan.config("essid")
            except Exception:
                pass
            try:
                out["rssi"] = wlan.status("rssi")
            except Exception:
                pass
    except Exception:
        pass
    return out


# ── power-mode preset cycling ────────────────────────────────────────────
# A single dial that covers TX dBm + power-save mode together so the user
# doesn't reason about both. Persisted on the OS settings dict so the
# choice survives a reboot.

POWER_MODES = ("off", "eco", "balanced", "max")

_MODE_TX_DBM = {"eco": 5, "balanced": 11, "max": 19}


def set_power_mode(mode):
    """Apply a coherent (tx_dbm, pm) preset to the live radio.

    'off'      → radio down
    'eco'      → 5 dBm, PM_POWERSAVE
    'balanced' → 11 dBm, PM_POWERSAVE (matches existing default)
    'max'      → 19 dBm, PM_NONE
    """
    if mode not in POWER_MODES:
        return False
    wlan = _get_wlan()
    if mode == "off":
        try:
            wlan.disconnect()
        except Exception:
            pass
        try:
            wlan.active(False)
        except Exception:
            pass
        return True

    try:
        wlan.active(True)
    except Exception:
        return False
    try:
        wlan.config(txpower=_MODE_TX_DBM[mode])
    except Exception:
        pass
    try:
        wlan.config(pm=(wlan.PM_NONE if mode == "max" else wlan.PM_POWERSAVE))
    except Exception:
        pass
    return True


def get_power_mode():
    """Best-effort introspection — returns the current preset name based
    on the active TX-power level and PM mode. Falls back to 'balanced'
    when MicroPython doesn't expose enough config to be sure."""
    try:
        wlan = _get_wlan()
        if not wlan.active():
            return "off"
        try:
            tx = int(wlan.config("txpower"))
        except Exception:
            return "balanced"
        if tx <= 6:
            return "eco"
        if tx >= 17:
            return "max"
        return "balanced"
    except Exception:
        return "balanced"
