"""WiFi manager for the Oreo Badge.

Saved networks live in `/wifi.json` on flash — a user-editable list
maintained by the WiFi settings app:

    [
      {"ssid": "Home",   "password": "...", "priority": 1, "metered": false},
      {"ssid": "Hotspot","password": "...", "priority": 5, "metered": true}
    ]

`connect_from_config()` walks the list in ascending-priority order
(lower number = tried first) and stops on the first SSID that
associates. `secrets.py` (generated by the deploy script) is only used
as a first-boot bootstrap: if `/wifi.json` doesn't exist yet AND
`secrets.WIFI_SSID` is set, we seed the json with that one network so
the badge associates immediately after the first flash.

Usage:
    from oreoWare import wifi
    wifi.connect_from_config()        # auto-pick best saved network
    wifi.is_connected()
    wifi.list_saved()                 # for the settings UI
    wifi.add_saved(ssid, pw, priority=10, metered=False)
    wifi.remove_saved(ssid)
    wifi.is_metered()                 # current link metered?
"""

import network
import time

try:
    import json as _json
except ImportError:
    _json = None

try:
    import os as _os
except ImportError:
    _os = None

_wlan = None

_SAVED_PATH       = "/wifi.json"
_PER_NET_TIMEOUT  = 10000    # ms — per-SSID cap. 10 s comfortably
                             # covers a cold DHCP lease on most home
                             # routers. The wait loop pumps a
                             # caller-supplied pump_cb every ~80 ms,
                             # so the UI is never frozen for the full
                             # duration — a keypress cancels instantly.


def _get_wlan():
    global _wlan
    if _wlan is None:
        _wlan = network.WLAN(network.STA_IF)
    return _wlan


def _apply_power_cap(wlan):
    """Apply the secrets-baked TX-power dBm cap + power-save mode.

    Done as a best-effort: every `wlan.config(...)` call is wrapped in
    try/except so older / minimal MicroPython builds without one of these
    keys don't kill WiFi entirely.
    """
    try:
        from secrets import WIFI_TX_DBM
        try:
            wlan.config(txpower=int(WIFI_TX_DBM))
        except Exception:
            pass
    except Exception:
        pass
    try:
        from secrets import WIFI_POWERSAVE
        if WIFI_POWERSAVE:
            try:
                wlan.config(pm=wlan.PM_POWERSAVE)
            except Exception:
                pass
    except Exception:
        pass


MDNS_HOSTNAME = "oreo"


_hostname_applied = False

def _apply_hostname(wlan):
    """Set the WiFi hostname so the ESP-IDF mDNS responder advertises
    `oreo.local` to the LAN. MicroPython builds vary in which kwarg key
    actually takes effect (`hostname` vs `dhcp_hostname`) so we try both.

    Idempotent + best-effort: a previous call's success means we never
    re-touch the radio configuration, and any failure is silent. We
    deliberately do NOT call `network.hostname()` here — that
    top-level setter exists on some ESP32 builds but has been
    observed to leave the radio in a half-initialised state when
    called between `active(True)` and `connect(...)`, which then
    makes every subsequent connect attempt fail. The per-WLAN
    `wlan.config()` form is enough for IDF's mDNS responder to pick
    up the hostname.
    """
    global _hostname_applied
    if _hostname_applied:
        return
    for key in ("hostname", "dhcp_hostname"):
        try:
            wlan.config(**{key: MDNS_HOSTNAME})
            _hostname_applied = True
        except Exception:
            # Build doesn't support this key, or radio rejected it.
            # Move on quietly.
            pass


def radio_on():
    """Power up the radio without trying to associate. Lets the user
    flip WiFi 'on' from the Settings page even when no saved network
    is reachable — keeps the toggle from feeling broken when the
    badge is somewhere with no known WiFi nearby."""
    try:
        wlan = _get_wlan()
        wlan.active(True)
        return True
    except Exception:
        return False


def radio_off():
    """Power the radio fully down. Releases any active connection
    cleanly and saves the ~70 mA the WiFi MAC pulls in idle. Pairs
    with `radio_on()` so a UI toggle has a real on/off semantic."""
    try:
        wlan = _get_wlan()
        try: wlan.disconnect()
        except Exception: pass
        try: wlan.active(False)
        except Exception: pass
        return True
    except Exception:
        return False


def is_radio_on():
    """True iff the WiFi MAC is powered up. Distinct from
    `is_connected()`, which only flips true after a full association.
    UI 'WiFi: ON/OFF' should track this — association state is a
    sub-label on the same row."""
    try:
        return bool(_get_wlan().active())
    except Exception:
        return False


def connect(ssid, password, timeout_ms=6000, pump_cb=None):
    """Initiate a WiFi association and wait (up to `timeout_ms`) for it
    to complete.

    `pump_cb` is the escape-hatch from the "badge looks frozen during
    SEARCH" trap: the wait loop calls it ~12 times per second and
    bails immediately if it returns truthy. Callers pass a pump that:
      1. Re-reads the button matrix.
      2. Returns True on any keypress so the user can abort.
    Boot-time auto-connect leaves pump_cb=None — the OS run loop
    isn't running yet there's nothing to keep alive — and just relies
    on the shorter timeout to bound the freeze.
    """
    wlan = _get_wlan()
    try:
        wlan.active(True)
    except Exception as e:
        print("[wifi] active(True) raised:", e)
        return False
    try:
        _apply_hostname(wlan)
    except Exception:
        pass
    try:
        _apply_power_cap(wlan)
    except Exception:
        pass
    try:
        if wlan.isconnected() and wlan.config("essid") == ssid:
            return True
    except Exception:
        pass
    try:
        wlan.connect(ssid, password)
    except Exception as e:
        print("[wifi] wlan.connect raised:", e)
        return False
    start = time.ticks_ms()
    while not wlan.isconnected():
        if time.ticks_diff(time.ticks_ms(), start) > timeout_ms:
            return False
        # Pump first so the very-first frame of "searching..." can be
        # cancelled. Sleep duration is intentionally short (~80 ms) so
        # button-to-cancel feels instant, but long enough that we don't
        # eat all the CPU we're trying to keep available.
        if pump_cb:
            try:
                if pump_cb():
                    print("[wifi] connect cancelled by pump_cb")
                    return False
            except Exception:
                pass
        time.sleep_ms(80)
    try:
        _apply_power_cap(wlan)
    except Exception:
        pass
    return True


def _exists(path):
    if _os is None:
        return False
    try:
        _os.stat(path)
        return True
    except OSError:
        return False


def _load_saved_raw():
    """Read `/wifi.json` as a Python list. Returns [] on missing/bad
    file — the caller is expected to bootstrap from secrets if so."""
    if _json is None or not _exists(_SAVED_PATH):
        return []
    try:
        with open(_SAVED_PATH) as f:
            data = _json.loads(f.read())
        if not isinstance(data, list):
            return []
        return data
    except Exception:
        return []


def _save_raw(networks):
    if _json is None:
        return False
    try:
        with open(_SAVED_PATH, "w") as f:
            f.write(_json.dumps(networks))
        return True
    except Exception:
        return False


def _bootstrap_from_secrets():
    """First-boot migration: if /wifi.json is missing AND secrets.py
    carries a single SSID, materialise it as a one-entry list. Idempotent
    — once /wifi.json exists this is a no-op."""
    if _exists(_SAVED_PATH):
        return _load_saved_raw()
    try:
        import secrets
        ssid = getattr(secrets, "WIFI_SSID", "")
        pw   = getattr(secrets, "WIFI_PASSWORD", "")
    except Exception:
        ssid, pw = "", ""
    if not ssid:
        return []
    seed = [{"ssid": ssid, "password": pw, "priority": 1, "metered": False}]
    _save_raw(seed)
    return seed


def list_saved():
    """Return the saved-networks list, sorted by ascending priority.
    Caller gets fresh dicts — mutating them doesn't affect on-disk state
    until save_saved() is called."""
    nets = _load_saved_raw() or _bootstrap_from_secrets()
    # Defensive copy + priority sort (None or missing → very high so
    # nameless entries sink to the bottom).
    def _key(n):
        try:
            return int(n.get("priority", 999))
        except Exception:
            return 999
    return sorted([dict(n) for n in nets if n.get("ssid")], key=_key)


def save_saved(networks):
    """Replace the entire saved list. Settings UI uses this after
    add / remove / reorder."""
    return _save_raw(list(networks))


def add_saved(ssid, password, priority=10, metered=False):
    """Add or update a single saved network. Matched by SSID; existing
    entries are overwritten so the user doesn't accumulate duplicates
    if they re-enter the same network."""
    nets = _load_saved_raw() or _bootstrap_from_secrets()
    out  = [n for n in nets if n.get("ssid") != ssid]
    out.append({
        "ssid":     ssid,
        "password": password or "",
        "priority": int(priority),
        "metered":  bool(metered),
    })
    return _save_raw(out)


def remove_saved(ssid):
    nets = _load_saved_raw()
    out  = [n for n in nets if n.get("ssid") != ssid]
    if len(out) == len(nets):
        return False
    return _save_raw(out)


def set_priority(ssid, priority):
    nets = _load_saved_raw()
    changed = False
    for n in nets:
        if n.get("ssid") == ssid:
            n["priority"] = int(priority)
            changed = True
            break
    if not changed:
        return False
    return _save_raw(nets)


def is_metered():
    """True iff the currently-associated SSID is flagged metered in
    /wifi.json. Used by OTA + Store to back off on tethered/hotspot
    connections so we don't burn the user's data plan."""
    cur = ssid()
    if not cur:
        return False
    for n in _load_saved_raw():
        if n.get("ssid") == cur:
            return bool(n.get("metered"))
    return False


def connect_from_config(pump_cb=None):
    """Try each saved network in priority order until one associates.

    Three-tier fallback so a freshly-flashed badge with an empty (or
    missing) /wifi.json still comes up online:

      1. /wifi.json — the user-managed list, edited via Settings → WiFi.
      2. secrets.py — the deploy-time single-network bootstrap. Used
         when /wifi.json exists but is empty (the user wiped it) AND
         when /wifi.json never existed and the on-flash migration in
         list_saved() didn't catch the gap.
      3. Otherwise: return False, radio stays off.

    Per-network timeout is short (_PER_NET_TIMEOUT) so a stale entry
    doesn't stall the boot.
    """
    nets = list_saved()
    if not nets:
        # Last-ditch: try the deploy-time secret directly. Without this
        # an empty /wifi.json silently disabled WiFi forever on freshly
        # flashed badges — the toggle on the Status row would call
        # connect_from_config(), find no saved nets, and bail without
        # ever bringing the radio up.
        try:
            import secrets
            ssid_ = getattr(secrets, "WIFI_SSID", "")
            pw    = getattr(secrets, "WIFI_PASSWORD", "")
            if ssid_:
                print("[wifi] no saved nets, falling back to secrets bootstrap")
                # Persist as the new "priority 1" entry so this branch
                # only fires once per device — subsequent connects use
                # the normal path.
                try:
                    add_saved(ssid_, pw, priority=1, metered=False)
                except Exception:
                    pass
                ok = False
                try:
                    ok = connect(ssid_, pw,
                                 timeout_ms=_PER_NET_TIMEOUT,
                                 pump_cb=pump_cb)
                except Exception:
                    pass
                return ok
        except Exception as e:
            print("[wifi] secrets bootstrap failed:", e)
        print("[wifi] no networks configured")
        return False
    for n in nets:
        ssid_ = n.get("ssid") or ""
        if not ssid_:
            continue
        pw = n.get("password") or ""
        try:
            print("[wifi] try %s (p=%s)" %
                  (ssid_, n.get("priority", "?")))
            ok = connect(ssid_, pw,
                         timeout_ms=_PER_NET_TIMEOUT,
                         pump_cb=pump_cb)
        except Exception as e:
            print("[wifi] connect raised:", e)
            ok = False
        if ok:
            print("[wifi] associated:", ssid_)
            return True
        # If the user cancelled mid-search, stop trying further
        # networks — they explicitly asked us to give up. Without
        # this we'd plough through every saved entry honouring their
        # individual timeouts.
        if pump_cb is not None:
            try:
                if pump_cb():
                    print("[wifi] connect_from_config cancelled")
                    return False
            except Exception:
                pass
    print("[wifi] all %d saved networks failed" % len(nets))
    return False


def disconnect():
    wlan = _get_wlan()
    wlan.disconnect()
    wlan.active(False)


def is_connected():
    try:
        return _get_wlan().isconnected()
    except Exception:
        return False


def ip():
    try:
        wlan = _get_wlan()
        if wlan.isconnected():
            return wlan.ifconfig()[0]
    except Exception:
        pass
    return None


def rssi():
    try:
        return _get_wlan().status("rssi")
    except Exception:
        return None


def ssid():
    """Currently-associated SSID, or None if not connected."""
    try:
        wlan = _get_wlan()
        if wlan.isconnected():
            return wlan.config("essid")
    except Exception:
        pass
    return None


def ping(host="8.8.8.8", port=53, timeout_s=2):
    """TCP-connect "ping" to a known endpoint. MicroPython doesn't ship
    raw ICMP sockets on this port, so we time the TCP handshake to a
    cheap target (Google's DNS on port 53 by default).

    Returns (ok, rtt_ms). `ok=False, rtt_ms=None` on failure.
    """
    try:
        import socket as _s
    except ImportError:
        return (False, None)
    if not is_connected():
        return (False, None)
    try:
        addr = _s.getaddrinfo(host, port)[0][-1]
    except Exception:
        return (False, None)
    sock = _s.socket()
    try:
        sock.settimeout(timeout_s)
    except Exception:
        pass
    t0 = time.ticks_ms()
    try:
        sock.connect(addr)
        rtt = time.ticks_diff(time.ticks_ms(), t0)
        return (True, rtt)
    except Exception:
        return (False, None)
    finally:
        try:
            sock.close()
        except Exception:
            pass


def speed_test(bytes_=200_000, timeout_s=10, pump_cb=None):
    """Throughput probe: download `bytes_` from speed.cloudflare.com
    and report observed kbps.

    `pump_cb` is called between every recv() so the caller can keep
    the OS run loop alive — typically passes a closure that re-reads
    the button matrix and bumps the screen. The socket is set to a
    50-ms recv timeout so each blocked read can't freeze the UI for
    more than that. If pump_cb returns True the test aborts cleanly
    (used by the WiFi app's "cancel by any keypress" UX).

    Default size dropped from 500 KB → 200 KB. The handshake is
    still amortised but the test finishes in ~1–2 s on home WiFi
    and ~5 s on weak links, both well within user attention span.

    Returns (ok, kbps, elapsed_ms). On failure or cancel,
    (False, 0, elapsed).
    """
    try:
        import socket as _s
        import ssl    as _ssl
    except ImportError:
        return (False, 0, 0)
    if not is_connected():
        return (False, 0, 0)
    host = "speed.cloudflare.com"
    path = "/__down?bytes=%d" % int(bytes_)
    try:
        addr = _s.getaddrinfo(host, 443)[0][-1]
    except Exception:
        return (False, 0, 0)

    raw = None
    s   = None
    deadline = time.ticks_add(time.ticks_ms(), int(timeout_s * 1000))
    t0 = time.ticks_ms()
    received = 0
    body_started = False
    cancelled = False

    # 50 ms recv timeout caps each blocking read so the run loop
    # can resume between reads. This is the difference between
    # "buttons frozen for 5 s" and "buttons responsive throughout".
    PER_READ_S = 0.05

    def _pump():
        """Run the caller's pump callback if any; flag cancel."""
        nonlocal cancelled
        if pump_cb is None:
            return
        try:
            if pump_cb():
                cancelled = True
        except Exception:
            pass

    try:
        raw = _s.socket()
        try: raw.settimeout(timeout_s)   # connect can take a while
        except Exception: pass
        raw.connect(addr)
        s = _ssl.wrap_socket(raw, server_hostname=host)
        try: s.settimeout(PER_READ_S)
        except Exception: pass
        req = ("GET %s HTTP/1.1\r\nHost: %s\r\n"
               "User-Agent: OreoBadge-Speed\r\n"
               "Accept-Encoding: identity\r\n"
               "Connection: close\r\n\r\n") % (path, host)
        s.write(req.encode())
        head = b""
        # Read headers. With the short PER_READ_S timeout each recv
        # bails fast on no-data; we loop until the separator arrives
        # or the overall deadline blows.
        while b"\r\n\r\n" not in head:
            if cancelled:
                break
            if time.ticks_diff(deadline, time.ticks_ms()) <= 0:
                break
            try:
                chunk = s.read(2048)
            except OSError:
                _pump()
                continue
            except Exception:
                break
            if not chunk:
                break
            head += chunk
            if len(head) > 16 * 1024:
                break
            _pump()
        sep = head.find(b"\r\n\r\n")
        if sep >= 0:
            body_started = True
            received = len(head) - (sep + 4)
        # Drain the body.
        while body_started:
            if cancelled:
                break
            if time.ticks_diff(deadline, time.ticks_ms()) <= 0:
                break
            try:
                chunk = s.read(4096)
            except OSError:
                _pump()
                continue
            except Exception:
                break
            if not chunk:
                break
            received += len(chunk)
            _pump()
            if received >= bytes_:
                break
    except Exception:
        pass
    finally:
        for h in (s, raw):
            try:
                if h is not None:
                    h.close()
            except Exception:
                pass
    elapsed = max(1, time.ticks_diff(time.ticks_ms(), t0))
    if cancelled:
        return (False, 0, elapsed)
    if received <= 0:
        return (False, 0, elapsed)
    kbps = int((received * 8) // elapsed)   # bytes*8 / ms = kbps
    return (True, kbps, elapsed)


def info():
    """One-shot snapshot for the WiFi detail screen.

    Returns a dict with `connected`, `ssid`, `ip`, `subnet`, `gateway`,
    `dns`, and `rssi`. Missing fields are None — the UI fills with '—'.
    """
    out = {"connected": False, "radio_on": False,
           "ssid": None,    "ip": None,
           "subnet":   None,  "gateway": None, "dns": None,
           "rssi":     None}
    try:
        wlan = _get_wlan()
        try:
            out["radio_on"] = bool(wlan.active())
        except Exception:
            pass
        out["connected"] = bool(wlan.isconnected())
        if out["connected"]:
            cfg = wlan.ifconfig()    # (ip, subnet, gateway, dns)
            out["ip"]      = cfg[0]
            out["subnet"]  = cfg[1]
            out["gateway"] = cfg[2]
            out["dns"]     = cfg[3]
            try:
                out["ssid"] = wlan.config("essid")
            except Exception:
                pass
            try:
                out["rssi"] = wlan.status("rssi")
            except Exception:
                pass
    except Exception:
        pass
    return out


# ── power-mode preset cycling ────────────────────────────────────────────
# A single dial that covers TX dBm + power-save mode together so the user
# doesn't reason about both. Persisted on the OS settings dict so the
# choice survives a reboot.

POWER_MODES = ("off", "eco", "balanced", "max")

_MODE_TX_DBM = {"eco": 5, "balanced": 11, "max": 19}


def set_power_mode(mode):
    """Apply a coherent (tx_dbm, pm) preset to the live radio.

    'off'      → radio down
    'eco'      → 5 dBm, PM_POWERSAVE
    'balanced' → 11 dBm, PM_POWERSAVE (matches existing default)
    'max'      → 19 dBm, PM_NONE
    """
    if mode not in POWER_MODES:
        return False
    wlan = _get_wlan()
    if mode == "off":
        try:
            wlan.disconnect()
        except Exception:
            pass
        try:
            wlan.active(False)
        except Exception:
            pass
        return True

    try:
        wlan.active(True)
    except Exception:
        return False
    try:
        wlan.config(txpower=_MODE_TX_DBM[mode])
    except Exception:
        pass
    try:
        wlan.config(pm=(wlan.PM_NONE if mode == "max" else wlan.PM_POWERSAVE))
    except Exception:
        pass
    return True


def get_power_mode():
    """Best-effort introspection — returns the current preset name based
    on the active TX-power level and PM mode. Falls back to 'balanced'
    when MicroPython doesn't expose enough config to be sure."""
    try:
        wlan = _get_wlan()
        if not wlan.active():
            return "off"
        try:
            tx = int(wlan.config("txpower"))
        except Exception:
            return "balanced"
        if tx <= 6:
            return "eco"
        if tx >= 17:
            return "max"
        return "balanced"
    except Exception:
        return "balanced"
